language: ruby
rvm:
  - 1.8.7
  - 1.9.2 # Test with vim-nox package on ubuntu
  - 1.9.3 # Test against python installer
  - 2.0.0

before_script: |
  if [ $(ruby -e 'puts RUBY_VERSION') = 1.9.2 ]; then
    sudo apt-get update -y
    sudo apt-get install -y vim-nox
    sudo ln -s /usr/bin/vim /usr/local/bin/vim
  else
    git clone --depth 1 https://github.com/vim/vim
    cd vim
    if [ $(ruby -e 'puts RUBY_VERSION') = 1.9.3 ]; then
      sudo apt-get update -y
      sudo apt-get install -y python2.7-dev
      ./configure --with-features=huge --enable-pythoninterp
    else
      ./configure --with-features=huge --enable-rubyinterp
    fi
    make
    sudo make install
    cd -
  fi

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

script: |
  test/run !
